### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Ismailco** [AyoubMs/catalog_of_my_things_ruby#30]
Github Project board: https://github.com/AyoubMs/catalog_of_my_things_ruby/projects/1

We are three students in this project,
 - Team member 1: @Ismailco 
 - Team member 2: @AyoubMs
 - Team member 3: @OybekKayumov

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Ismailco, @OybekKayumov and @AyoubMs,

Good job so far!
✔️ Kanban board has the correct number of columns
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Some of your tasks are missing the allocated number of points. Kindly add them.

  ![xpt](https://user-images.githubusercontent.com/36542986/175913013-07bd4efc-9937-4dd0-93ca-205502250885.jpg)

- [ ] The following tasks do not have proper descriptions. Kindly add them.

  Image 1 | Image 2
  :---:|:---:
  ![musicalbum](https://user-images.githubusercontent.com/36542986/175913630-c053da60-852a-4448-8411-3d5d0a25334e.jpg) | ![ayoub-descr](https://user-images.githubusercontent.com/36542986/175913615-e7855972-51e0-47b2-ae79-2d2f1ada1ebc.jpg)

  Figure 3 | Figure 4
  :---:|:---:
  ![tasks-with-descr](https://user-images.githubusercontent.com/36542986/175913624-f2cfd7fa-456b-4443-979e-480ca2ae3adb.jpg) | ![genre](https://user-images.githubusercontent.com/36542986/175913627-b27ad522-17d2-4321-b9ea-497523c94f0a.jpg)

- [x] The total number of task points assigned to a team member is required to be less than 5 in comparison to another member. @Ismailco total points are 29pts; @OybekKayumov total points are 33pts; @AyoubMs has 50 points. Kindly re-allocate your points.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
Hi @Ismailco, @OybekKayumov and @AyoubMs, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly ensure that all the tasks have the required description. The task in the attachment does not have a description so, kindly add it.
<img width="197" alt="chrome_kpKS9cybfq" src="https://user-images.githubusercontent.com/81468675/175937720-290727cd-4ba3-4f75-835b-136145c4b1da.png">



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
